"""adiciona campo ativo aos itens da ficha

Revision ID: 222f16e3ce67
Revises: a8763bd62273
Create Date: 2026-09-04 13:15:59.962763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222f16e3ce67'
down_revision: Union[str, Sequence[str], None] = 'a8763bd62273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_ficha', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_ficha', 'ativo')
    # ### end Alembic commands ###
