"""adiciona campo ativo aos exercicios

Revision ID: 6a10c065d3ca
Revises: 81d766226503
Create Date: 2026-09-08 12:44:25.996663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a10c065d3ca'
down_revision: Union[str, Sequence[str], None] = '81d766226503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercicios', sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercicios', 'ativo')
    # ### end Alembic commands ###
