"""adiciona campo ativo em ficha

Revision ID: 7bb72965c3b5
Revises: 222f16e3ce67
Create Date: 2026-09-04 14:00:03.279460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb72965c3b5'
down_revision: Union[str, Sequence[str], None] = '222f16e3ce67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fichas', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fichas', 'ativo')
    # ### end Alembic commands ###
