"""adiciona ordem em item_ficha

Revision ID: 81d766226503
Revises: e4444f75bdc7
Create Date: 2026-09-06 15:06:58.741830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d766226503'
down_revision: Union[str, Sequence[str], None] = 'e4444f75bdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_ficha', sa.Column('ordem', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_ficha', 'ordem')
    # ### end Alembic commands ###
