"""adiciona campos de imagem e video aos exercicios

Revision ID: 8eadc8e42751
Revises: 922c5e7b10be
Create Date: 2026-09-01 17:16:34.656017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eadc8e42751'
down_revision: Union[str, Sequence[str], None] = '922c5e7b10be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercicios', sa.Column('imagem', sa.String(length=500), nullable=True))
    op.add_column('exercicios', sa.Column('video', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercicios', 'video')
    op.drop_column('exercicios', 'imagem')
    # ### end Alembic commands ###
