"""Adiciona campo de foto ao usuário

Revision ID: 922c5e7b10be
Revises: 2b58ed61c57b
Create Date: 2026-09-01 13:08:11.278104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922c5e7b10be'
down_revision: Union[str, Sequence[str], None] = '2b58ed61c57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foto')
    # ### end Alembic commands ###
