"""adiciona public ids das midias dos exercicios

Revision ID: a8763bd62273
Revises: 8eadc8e42751
Create Date: 2026-09-03 12:20:06.049596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8763bd62273'
down_revision: Union[str, Sequence[str], None] = '8eadc8e42751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercicios', sa.Column('imagem_public_id', sa.String(length=500), nullable=True))
    op.add_column('exercicios', sa.Column('video_public_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercicios', 'video_public_id')
    op.drop_column('exercicios', 'imagem_public_id')
    # ### end Alembic commands ###
