"""adiciona relacionamento entre treino e item da ficha

Revision ID: e4444f75bdc7
Revises: 6fe02949a3b7
Create Date: 2026-09-06 13:40:18.398992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4444f75bdc7'
down_revision: Union[str, Sequence[str], None] = '6fe02949a3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_ficha', sa.Column('treino_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'itens_ficha', 'treino', ['treino_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itens_ficha', type_='foreignkey')
    op.drop_column('itens_ficha', 'treino_id')
    # ### end Alembic commands ###
